import { Lead } from "@/types/leads";

// A compact synthesized sample audio wav file (data URI) for testing real HTML5 playback & 'ended' event
// A short beep/tone audio file that plays smoothly in browser for ~6 seconds
export const SAMPLE_AUDIO_DATA_URI = "data:audio/wav;base64,UklGRjIAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YRAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

// Reliable local demo call recording
export const DEMO_AUDIO_URL = "/audio/sample-call.wav";

export const INITIAL_MOCK_LEADS: Lead[] = [
  // 1. Marketing Leads (Newly entered)
  {
    id: "lead-001",
    leadCode: "VA-2026-1001",
    name: "Rajesh Kulkarni",
    contactNumber: "+91 98230 45129",
    city: "Pune",
    state: "Maharashtra",
    currentDepartment: "marketing",
    status: "new",
    createdAt: "2026-09-28T09:15:00Z",
    updatedAt: "2026-09-28T09:15:00Z",
    createdBy: "Rohan Varma (Marketing)",
    remark: "Inbound inquiry via Cloud ERP campaign. Expressed interest in enterprise multi-branch licensing.",
    workflowHistory: [
      {
        id: "wf-1001-1",
        department: "marketing",
        action: "Lead Captured",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-28T09:15:00Z",
        description: "Inbound campaign submission recorded from official portal.",
      },
    ],
  },
  {
    id: "lead-002",
    leadCode: "VA-2026-1002",
    name: "Sunita Nambiar",
    contactNumber: "+91 94471 88234",
    city: "Kochi",
    state: "Kerala",
    currentDepartment: "marketing",
    status: "new",
    createdAt: "2026-09-28T11:40:00Z",
    updatedAt: "2026-09-28T11:40:00Z",
    createdBy: "Rohan Varma (Marketing)",
    remark: "Referral from Logistics Summit 2026. Needs supply chain integration details.",
    workflowHistory: [
      {
        id: "wf-1002-1",
        department: "marketing",
        action: "Lead Captured",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-28T11:40:00Z",
        description: "Registered lead from Bangalore B2B Tech Expo delegate list.",
      },
    ],
  },
  {
    id: "lead-003",
    leadCode: "VA-2026-1003",
    name: "Amitabh Banerjee",
    contactNumber: "+91 98302 99401",
    city: "Kolkata",
    state: "West Bengal",
    currentDepartment: "marketing",
    status: "new",
    createdAt: "2026-09-29T08:20:00Z",
    updatedAt: "2026-09-29T08:20:00Z",
    createdBy: "Rohan Varma (Marketing)",
    remark: "Direct web form inquiry for manufacturing floor automated QA tracking.",
    workflowHistory: [
      {
        id: "wf-1003-1",
        department: "marketing",
        action: "Lead Captured",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-29T08:20:00Z",
        description: "Direct web lead received via Vibh-Anu Solutions Landing Page.",
      },
    ],
  },

  // 2. Communication Leads (Under discussion, waiting for meeting schedule)
  {
    id: "lead-004",
    leadCode: "VA-2026-1004",
    name: "Harishankar Iyer",
    contactNumber: "+91 97909 31450",
    postalAddress: "402, Ramanujan IT City, Taramani",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600113",
    date: "2026-10-02",
    time: "11:30 AM",
    remark: "Interested in 50-user tier with custom single-sign-on integration.",
    currentDepartment: "communication",
    status: "in_progress",
    createdAt: "2026-09-27T10:15:00Z",
    updatedAt: "2026-09-28T14:30:00Z",
    createdBy: "Rohan Varma (Marketing)",
    workflowHistory: [
      {
        id: "wf-1004-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-27T10:15:00Z",
        description: "Lead generated from LinkedIn B2B ad campaign.",
      },
      {
        id: "wf-1004-2",
        department: "communication",
        action: "Initial Contact Established",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-28T14:30:00Z",
        description: "Connected on phone. Prospect requested address confirmation and meeting slot.",
      },
    ],
  },
  {
    id: "lead-005",
    leadCode: "VA-2026-1005",
    name: "Meenakshi Sundaresan",
    contactNumber: "+91 98401 22910",
    postalAddress: "Plot 18, Guindy Industrial Estate",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    date: "2026-10-03",
    time: "03:00 PM",
    remark: "Follow-up required with CTO regarding on-premise security policies.",
    currentDepartment: "communication",
    status: "in_progress",
    createdAt: "2026-09-27T14:00:00Z",
    updatedAt: "2026-09-28T16:00:00Z",
    createdBy: "Rohan Varma (Marketing)",
    workflowHistory: [
      {
        id: "wf-1005-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-27T14:00:00Z",
        description: "Inbound request from healthcare diagnostics vendor.",
      },
      {
        id: "wf-1005-2",
        department: "communication",
        action: "Call Attempt #1",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-28T16:00:00Z",
        description: "Spoke with procurement team. Scheduled technical briefing.",
      },
    ],
  },
  {
    id: "lead-006",
    leadCode: "VA-2026-1006",
    name: "Gurpreet Singh Dhillon",
    contactNumber: "+91 98140 76543",
    postalAddress: "SCO 88-89, Sector 34-A",
    city: "Chandigarh",
    state: "Punjab",
    pincode: "160022",
    date: "2026-10-04",
    time: "04:30 PM",
    remark: "Agri-export firm looking for warehouse inventory workflow automation.",
    currentDepartment: "communication",
    status: "in_progress",
    createdAt: "2026-09-28T09:00:00Z",
    updatedAt: "2026-09-29T10:00:00Z",
    createdBy: "Rohan Varma (Marketing)",
    workflowHistory: [
      {
        id: "wf-1006-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-28T09:00:00Z",
        description: "Captured via Punjab Chamber of Commerce directory outreach.",
      },
    ],
  },

  // 3. Vigilance Leads (Meeting fixed, waiting for audit + audio upload)
  {
    id: "lead-007",
    leadCode: "VA-2026-1007",
    name: "Pradeep Reddy",
    contactNumber: "+91 98490 65123",
    postalAddress: "8-2-293/82/A, Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500033",
    date: "2026-10-01",
    time: "02:00 PM",
    remark: "Meeting scheduled. KYC & GST document verification pending verification call recording.",
    currentDepartment: "vigilance",
    status: "meeting_scheduled",
    createdAt: "2026-09-25T11:00:00Z",
    updatedAt: "2026-09-28T12:30:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-10-01",
      scheduledTime: "02:00 PM",
      meetingNotes: "Client confirmed address and authorized representative details.",
      completedAt: "2026-09-28T12:30:00Z",
      completedBy: "Pooja Hegde",
    },
    workflowHistory: [
      {
        id: "wf-1007-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-25T11:00:00Z",
        description: "Registered lead from Cyberabad IT showcase.",
      },
      {
        id: "wf-1007-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-28T12:30:00Z",
        description: "Scheduled verification briefing for Oct 01, 2:00 PM. Transferred to Vigilance.",
      },
    ],
  },
  {
    id: "lead-008",
    leadCode: "VA-2026-1008",
    name: "Kavita Singhania",
    contactNumber: "+91 98200 44987",
    postalAddress: "Floor 14, Maker Chambers IV, Nariman Point",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400021",
    date: "2026-10-01",
    time: "10:30 AM",
    remark: "Corporate legal compliance check required. Call recording mandatory before clearance.",
    currentDepartment: "vigilance",
    status: "meeting_scheduled",
    createdAt: "2026-09-26T15:20:00Z",
    updatedAt: "2026-09-28T17:45:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-10-01",
      scheduledTime: "10:30 AM",
      meetingNotes: "Confirmed meeting with Head of Operations.",
      completedAt: "2026-09-28T17:45:00Z",
      completedBy: "Pooja Hegde",
    },
    workflowHistory: [
      {
        id: "wf-1008-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-26T15:20:00Z",
        description: "Financial services lead captured from BFSI conference.",
      },
      {
        id: "wf-1008-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-28T17:45:00Z",
        description: "Meeting scheduled. Forwarded to Vigilance for authentication.",
      },
    ],
  },

  // 4. Support Leads (Verified with Audio, waiting for 3-point check & Sales Allocation)
  {
    id: "lead-009",
    leadCode: "VA-2026-1009",
    name: "Deepak Chawla",
    contactNumber: "+91 98110 54321",
    postalAddress: "Tower B, DLF Cyber City, Phase III",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122002",
    date: "2026-09-30",
    time: "11:00 AM",
    remark: "Vigilance audit passed. Audio recording attached. Awaiting Support allocation to Sales executive.",
    currentDepartment: "support",
    status: "verified",
    createdAt: "2026-09-24T09:30:00Z",
    updatedAt: "2026-09-28T15:10:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-09-30",
      scheduledTime: "11:00 AM",
      meetingNotes: "Full enterprise demo arranged.",
      completedAt: "2026-09-26T14:00:00Z",
      completedBy: "Pooja Hegde",
    },
    vigilanceDetails: {
      audio: {
        id: "aud-1009",
        fileName: "Vigilance_Call_DeepakChawla_DLF.mp3",
        fileSize: 3450000,
        duration: 184, // 3m 04s
        url: DEMO_AUDIO_URL,
        uploadedAt: "2026-09-28T15:10:00Z",
        uploadedBy: "Vikram Malhotra (Vigilance)",
        mimeType: "audio/mpeg",
        waveformSample: [18, 35, 60, 80, 45, 90, 75, 40, 65, 85, 95, 70, 50, 60, 40, 80, 55, 30],
      },
      verificationNotes: "Identity verified against MCA corporate records. Audio consent received.",
      completedAt: "2026-09-28T15:10:00Z",
      completedBy: "Vikram Malhotra",
    },
    supportDetails: {
      verification: {
        isDateVerified: false,
        isTimeVerified: false,
        isAddressVerified: false,
      },
    },
    workflowHistory: [
      {
        id: "wf-1009-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-24T09:30:00Z",
        description: "Lead generated via Google Ads Enterprise Suite.",
      },
      {
        id: "wf-1009-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-26T14:00:00Z",
        description: "Scheduled discovery call and locked phone contact.",
      },
      {
        id: "wf-1009-3",
        department: "vigilance",
        action: "Verified & Audio Uploaded",
        userName: "Vikram Malhotra",
        userRole: "VIGILANCE",
        timestamp: "2026-09-28T15:10:00Z",
        description: "Vigilance audit complete. Uploaded verified voice recording (3:04).",
      },
    ],
  },
  {
    id: "lead-010",
    leadCode: "VA-2026-1010",
    name: "Aniruddha Sen",
    contactNumber: "+91 98311 90876",
    postalAddress: "Sector V, Salt Lake Electronics Complex",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700091",
    date: "2026-10-02",
    time: "03:30 PM",
    remark: "Audio verified. Ready for support team assignment.",
    currentDepartment: "support",
    status: "verified",
    createdAt: "2026-09-24T14:00:00Z",
    updatedAt: "2026-09-28T16:20:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-10-02",
      scheduledTime: "03:30 PM",
      meetingNotes: "Discussion with regional operations lead.",
      completedAt: "2026-09-26T16:00:00Z",
      completedBy: "Pooja Hegde",
    },
    vigilanceDetails: {
      audio: {
        id: "aud-1010",
        fileName: "Vigilance_Record_AniruddhaSen.mp3",
        fileSize: 2890000,
        duration: 142,
        url: DEMO_AUDIO_URL,
        uploadedAt: "2026-09-28T16:20:00Z",
        uploadedBy: "Vikram Malhotra (Vigilance)",
        mimeType: "audio/mpeg",
        waveformSample: [20, 45, 70, 60, 85, 90, 40, 30, 60, 75, 80, 50, 40, 65, 30, 20],
      },
      verificationNotes: "Address and executive title verified.",
      completedAt: "2026-09-28T16:20:00Z",
      completedBy: "Vikram Malhotra",
    },
    supportDetails: {
      verification: {
        isDateVerified: false,
        isTimeVerified: false,
        isAddressVerified: false,
      },
    },
    workflowHistory: [
      {
        id: "wf-1010-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-24T14:00:00Z",
        description: "Trade fair lead entry.",
      },
      {
        id: "wf-1010-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-26T16:00:00Z",
        description: "Meeting set up for Oct 02.",
      },
      {
        id: "wf-1010-3",
        department: "vigilance",
        action: "Verified & Audio Uploaded",
        userName: "Vikram Malhotra",
        userRole: "VIGILANCE",
        timestamp: "2026-09-28T16:20:00Z",
        description: "Verified customer credentials. Attached compliance recording.",
      },
    ],
  },

  // 5. Sales Leads (Allocated to Sales queue, requires full audio listen to Claim)
  {
    id: "lead-011",
    leadCode: "VA-2026-1011",
    name: "Shalini Murthy",
    contactNumber: "+91 99000 12345",
    postalAddress: "Prestige Tech Park, Marathahalli-Sarjapur Ring Road",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560103",
    date: "2026-09-29",
    time: "04:00 PM",
    remark: "Allocated to Sales queue. High-priority enterprise deal. Listen to full audio recording before claiming.",
    currentDepartment: "sales",
    status: "allocated",
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-29T10:15:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-09-29",
      scheduledTime: "04:00 PM",
      meetingNotes: "Chief Information Security Officer attended discovery.",
      completedAt: "2026-09-24T11:00:00Z",
      completedBy: "Pooja Hegde",
    },
    vigilanceDetails: {
      audio: {
        id: "aud-1011",
        fileName: "Vigilance_Call_ShaliniMurthy_Prestige.mp3",
        fileSize: 4200000,
        duration: 215, // 3m 35s
        url: DEMO_AUDIO_URL,
        uploadedAt: "2026-09-27T10:00:00Z",
        uploadedBy: "Vikram Malhotra (Vigilance)",
        mimeType: "audio/mpeg",
        waveformSample: [15, 30, 55, 75, 90, 85, 60, 45, 70, 80, 95, 65, 50, 40, 70, 85, 60, 30],
      },
      verificationNotes: "Entity and billing address validated with Ministry of Corporate Affairs.",
      completedAt: "2026-09-27T10:00:00Z",
      completedBy: "Vikram Malhotra",
    },
    supportDetails: {
      verification: {
        isDateVerified: true,
        isTimeVerified: true,
        isAddressVerified: true,
        verifiedBy: "Neha Sundaram",
        verifiedAt: "2026-09-29T10:15:00Z",
        notes: "All 3 verification points validated. Allocated to Enterprise Sales pool.",
      },
      allocatedTo: "Aditya Deshmukh",
      allocationNotes: "Urgent turnaround requested by client.",
      completedAt: "2026-09-29T10:15:00Z",
      completedBy: "Neha Sundaram",
    },
    salesDetails: {
      audioListenCompleted: false, // Initially false: Claim button MUST be disabled until natural audio ended event!
    },
    workflowHistory: [
      {
        id: "wf-1011-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-22T08:00:00Z",
        description: "Enterprise campaign lead generated.",
      },
      {
        id: "wf-1011-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-24T11:00:00Z",
        description: "Briefing confirmed with client VP.",
      },
      {
        id: "wf-1011-3",
        department: "vigilance",
        action: "Verified & Audio Uploaded",
        userName: "Vikram Malhotra",
        userRole: "VIGILANCE",
        timestamp: "2026-09-27T10:00:00Z",
        description: "Call recorded & verified compliance with company guidelines.",
      },
      {
        id: "wf-1011-4",
        department: "support",
        action: "Allocated to Sales",
        userName: "Neha Sundaram",
        userRole: "SUPPORT",
        timestamp: "2026-09-29T10:15:00Z",
        description: "Verified date, time, and address. Transferred to Sales queue.",
      },
    ],
  },
  {
    id: "lead-012",
    leadCode: "VA-2026-1012",
    name: "Tanmay Bhasin",
    contactNumber: "+91 98711 33221",
    postalAddress: "Block E, Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110001",
    date: "2026-09-30",
    time: "02:30 PM",
    remark: "Allocated. Audio recording available for listening prior to claiming.",
    currentDepartment: "sales",
    status: "allocated",
    createdAt: "2026-09-23T11:00:00Z",
    updatedAt: "2026-09-29T11:45:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-09-30",
      scheduledTime: "02:30 PM",
      meetingNotes: "Lead qualification call complete.",
      completedAt: "2026-09-25T12:00:00Z",
      completedBy: "Pooja Hegde",
    },
    vigilanceDetails: {
      audio: {
        id: "aud-1012",
        fileName: "Vigilance_Call_TanmayBhasin_CP.mp3",
        fileSize: 3100000,
        duration: 165,
        url: DEMO_AUDIO_URL,
        uploadedAt: "2026-09-27T14:30:00Z",
        uploadedBy: "Vikram Malhotra (Vigilance)",
        mimeType: "audio/mpeg",
        waveformSample: [25, 40, 65, 80, 70, 85, 90, 60, 45, 50, 75, 80, 40, 30],
      },
      verificationNotes: "Verified registered office in New Delhi.",
      completedAt: "2026-09-27T14:30:00Z",
      completedBy: "Vikram Malhotra",
    },
    supportDetails: {
      verification: {
        isDateVerified: true,
        isTimeVerified: true,
        isAddressVerified: true,
        verifiedBy: "Neha Sundaram",
        verifiedAt: "2026-09-29T11:45:00Z",
      },
      allocatedTo: "Aditya Deshmukh",
      completedAt: "2026-09-29T11:45:00Z",
      completedBy: "Neha Sundaram",
    },
    salesDetails: {
      audioListenCompleted: false,
    },
    workflowHistory: [
      {
        id: "wf-1012-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-23T11:00:00Z",
        description: "Lead captured from direct search inquiry.",
      },
      {
        id: "wf-1012-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-25T12:00:00Z",
        description: "Scheduled product demo for Sept 30.",
      },
      {
        id: "wf-1012-3",
        department: "vigilance",
        action: "Verified & Audio Uploaded",
        userName: "Vikram Malhotra",
        userRole: "VIGILANCE",
        timestamp: "2026-09-27T14:30:00Z",
        description: "Verified GSTIN and recorded compliance check.",
      },
      {
        id: "wf-1012-4",
        department: "support",
        action: "Allocated to Sales",
        userName: "Neha Sundaram",
        userRole: "SUPPORT",
        timestamp: "2026-09-29T11:45:00Z",
        description: "Passed 3-point check and allocated to Sales.",
      },
    ],
  },

  // 6. Claimed Leads (Completed full lifecycle: Claimed by Sales Executive)
  {
    id: "lead-013",
    leadCode: "VA-2026-1013",
    name: "Vikramaditya Rawat",
    contactNumber: "+91 98290 87654",
    postalAddress: "C-Scheme, Ashok Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    date: "2026-09-28",
    time: "11:00 AM",
    remark: "Successfully claimed by Sales Executive after complete audio review.",
    currentDepartment: "claimed",
    status: "claimed",
    createdAt: "2026-09-20T10:00:00Z",
    updatedAt: "2026-09-29T12:30:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-09-28",
      scheduledTime: "11:00 AM",
      meetingNotes: "Comprehensive overview presentation given.",
      completedAt: "2026-09-22T15:00:00Z",
      completedBy: "Pooja Hegde",
    },
    vigilanceDetails: {
      audio: {
        id: "aud-1013",
        fileName: "Vigilance_Call_VikramadityaRawat_Jaipur.mp3",
        fileSize: 3800000,
        duration: 195,
        url: DEMO_AUDIO_URL,
        uploadedAt: "2026-09-24T11:30:00Z",
        uploadedBy: "Vikram Malhotra (Vigilance)",
        mimeType: "audio/mpeg",
        waveformSample: [30, 45, 60, 80, 95, 80, 65, 70, 85, 90, 75, 60, 45, 30],
      },
      verificationNotes: "Audit verified and confirmed.",
      completedAt: "2026-09-24T11:30:00Z",
      completedBy: "Vikram Malhotra",
    },
    supportDetails: {
      verification: {
        isDateVerified: true,
        isTimeVerified: true,
        isAddressVerified: true,
        verifiedBy: "Neha Sundaram",
        verifiedAt: "2026-09-26T16:00:00Z",
      },
      allocatedTo: "Aditya Deshmukh",
      completedAt: "2026-09-26T16:00:00Z",
      completedBy: "Neha Sundaram",
    },
    salesDetails: {
      audioListenCompleted: true,
      claimedBy: "Aditya Deshmukh (Sales Executive)",
      claimedAt: "2026-09-29T12:30:00Z",
      dealValue: 450000,
      closingRemarks: "Client accepted proposal for 25 annual enterprise licenses. Contract drafting initiated.",
    },
    workflowHistory: [
      {
        id: "wf-1013-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-20T10:00:00Z",
        description: "Lead generated through Rajasthan IT conclave.",
      },
      {
        id: "wf-1013-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-22T15:00:00Z",
        description: "Scheduled meeting for Sept 28, 11:00 AM.",
      },
      {
        id: "wf-1013-3",
        department: "vigilance",
        action: "Verified & Audio Uploaded",
        userName: "Vikram Malhotra",
        userRole: "VIGILANCE",
        timestamp: "2026-09-24T11:30:00Z",
        description: "Verified KYC documents and uploaded telephone audit recording.",
      },
      {
        id: "wf-1013-4",
        department: "support",
        action: "Allocated to Sales",
        userName: "Neha Sundaram",
        userRole: "SUPPORT",
        timestamp: "2026-09-26T16:00:00Z",
        description: "3-point validation confirmed. Transferred to Sales queue.",
      },
      {
        id: "wf-1013-5",
        department: "sales",
        action: "Audio Listened & Lead Claimed",
        userName: "Aditya Deshmukh",
        userRole: "SALES",
        timestamp: "2026-09-29T12:30:00Z",
        description: "Completed full audio listening. Claimed lead and initiated deal onboarding (₹4,50,000).",
      },
    ],
  },
  {
    id: "lead-014",
    leadCode: "VA-2026-1014",
    name: "Radhika Kirloskar",
    contactNumber: "+91 98450 11223",
    postalAddress: "Lavelle Road, Shanthala Nagar",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560001",
    date: "2026-09-27",
    time: "10:00 AM",
    remark: "Enterprise contract finalized and claimed.",
    currentDepartment: "claimed",
    status: "claimed",
    createdAt: "2026-09-18T09:00:00Z",
    updatedAt: "2026-09-28T18:00:00Z",
    createdBy: "Rohan Varma (Marketing)",
    communicationDetails: {
      scheduledDate: "2026-09-27",
      scheduledTime: "10:00 AM",
      meetingNotes: "Executive walkthrough completed.",
      completedAt: "2026-09-20T11:00:00Z",
      completedBy: "Pooja Hegde",
    },
    vigilanceDetails: {
      audio: {
        id: "aud-1014",
        fileName: "Vigilance_Call_RadhikaKirloskar.mp3",
        fileSize: 4500000,
        duration: 230,
        url: DEMO_AUDIO_URL,
        uploadedAt: "2026-09-23T14:00:00Z",
        uploadedBy: "Vikram Malhotra (Vigilance)",
        mimeType: "audio/mpeg",
        waveformSample: [40, 55, 70, 85, 90, 75, 60, 50, 70, 85, 95, 70, 55, 40],
      },
      verificationNotes: "Audit verified and confirmed.",
      completedAt: "2026-09-23T14:00:00Z",
      completedBy: "Vikram Malhotra",
    },
    supportDetails: {
      verification: {
        isDateVerified: true,
        isTimeVerified: true,
        isAddressVerified: true,
        verifiedBy: "Neha Sundaram",
        verifiedAt: "2026-09-25T15:00:00Z",
      },
      allocatedTo: "Aditya Deshmukh",
      completedAt: "2026-09-25T15:00:00Z",
      completedBy: "Neha Sundaram",
    },
    salesDetails: {
      audioListenCompleted: true,
      claimedBy: "Aditya Deshmukh (Sales Executive)",
      claimedAt: "2026-09-28T18:00:00Z",
      dealValue: 820000,
      closingRemarks: "Multi-year enterprise agreement closed.",
    },
    workflowHistory: [
      {
        id: "wf-1014-1",
        department: "marketing",
        action: "Lead Created",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-18T09:00:00Z",
        description: "Enterprise inquiry recorded.",
      },
      {
        id: "wf-1014-2",
        department: "communication",
        action: "Meeting Scheduled",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-20T11:00:00Z",
        description: "Meeting locked with board representative.",
      },
      {
        id: "wf-1014-3",
        department: "vigilance",
        action: "Verified & Audio Uploaded",
        userName: "Vikram Malhotra",
        userRole: "VIGILANCE",
        timestamp: "2026-09-23T14:00:00Z",
        description: "Uploaded verification recording.",
      },
      {
        id: "wf-1014-4",
        department: "support",
        action: "Allocated to Sales",
        userName: "Neha Sundaram",
        userRole: "SUPPORT",
        timestamp: "2026-09-25T15:00:00Z",
        description: "Allocated to enterprise sales lead.",
      },
      {
        id: "wf-1014-5",
        department: "sales",
        action: "Audio Listened & Lead Claimed",
        userName: "Aditya Deshmukh",
        userRole: "SALES",
        timestamp: "2026-09-28T18:00:00Z",
        description: "Full audio listened. Lead claimed for ₹8,20,000 deal.",
      },
    ],
  },
  {
    id: "lead-015",
    leadCode: "VA-2026-1015",
    name: "Siddharth Nambiar",
    contactNumber: "+91 97400 55432",
    postalAddress: "MG Road, Camp",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001",
    date: "2026-10-05",
    time: "11:30 AM",
    remark: "Fintech integration inquiry with custom CRM connectors.",
    currentDepartment: "marketing",
    status: "new",
    createdAt: "2026-09-29T11:10:00Z",
    updatedAt: "2026-09-29T11:10:00Z",
    createdBy: "Rohan Varma (Marketing)",
    workflowHistory: [
      {
        id: "wf-1015-1",
        department: "marketing",
        action: "Lead Captured",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-29T11:10:00Z",
        description: "Captured via Organic Search on Vibh-Anu platform.",
      },
    ],
  },
  {
    id: "lead-016",
    leadCode: "VA-2026-1016",
    name: "Bhavna Somaiya",
    contactNumber: "+91 98250 67890",
    postalAddress: "SG Highway, Bodakdev",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380054",
    date: "2026-10-03",
    time: "02:15 PM",
    remark: "Textile conglomerate seeking unified sales & dispatch pipeline.",
    currentDepartment: "communication",
    status: "in_progress",
    createdAt: "2026-09-27T16:30:00Z",
    updatedAt: "2026-09-28T10:00:00Z",
    createdBy: "Rohan Varma (Marketing)",
    workflowHistory: [
      {
        id: "wf-1016-1",
        department: "marketing",
        action: "Lead Captured",
        userName: "Rohan Varma",
        userRole: "MARKETING",
        timestamp: "2026-09-27T16:30:00Z",
        description: "Gujarat Industrial Expo lead list.",
      },
      {
        id: "wf-1016-2",
        department: "communication",
        action: "Discussion Initiated",
        userName: "Pooja Hegde",
        userRole: "COMMUNICATION",
        timestamp: "2026-09-28T10:00:00Z",
        description: "Connected with GM Operations. Address updated.",
      },
    ],
  },
];
